<ul>
    <li>
        Version 2.0-beta2 - 2019-09-04
        <ul>
            <li>Bug fixes wrt to admin blocks editing</li>
            <li>Bug fix in PHP7.2+</li>
            <li>More to come especially for CMS Made Simple 2.3</li>
        </ul>
    </li>
    <li>Version 2.0 - since sept 2017
        <ul>
            <li>CMSMS 2.1.6+ ready</li>
            <li>removed the 'detector' stuff (doesn't work properly with CMSMS 2* for the moment) - you must use {MleCMS action=init} on the top of your page template</li>
            <li>add mle_selflink (mle version of cms_selflink)</li>
            <li>some admin changes</li>
            <li>now is not lazy loaded anymore in the admin, in order to work properly with 3rd party modules like CGBetterForms
            <li>bug fixes</li>
        </ul>
    </li>
    
    <li>Version 1.11.4 - december 2012 <br />
        - add support for external detection GetMleInit (see MleDomains for expample)<br />
        - fix page search results<br />    
        - fixed some bugs<br />    
    </li>
    <li>Version 1.11.3 - july 2012 <br />
        - add new CmsNlsOperations::set_language_detector support for CMSMS <br />
        - disable LazyLoadFrontend <br />
        - remove unnecessary option - Mle identifier (will be replaced another extensions for detection), Separator between langs (directly edit the template), Default params for translator action (use cge_module_hint from CGExtensions)
    </li>
    <li>Version 1.11.2 - july 2012 - fix auto language redirection</li>
    <li>Version 1.11.1 - july 2012 - translator reworked (XML files bye bye)</li>
    <li>Version 1.11 - july 2012 - CMSMS 1.11 support</li>
    <li>Version 1.10.5 - november 2011 - setlocale, extra param</li>
    <li>Version 1.4 - 1.7 - april 2011 - som small updates</li>
    <li>Version 1.3 - january 2011 - new millestone - Mle Translator</li>
    <li>Version 1.2 - january 2011 - new millestone - auto redirection</li>
    <li>Version 1.1 - january 2011 - small update</li>
    <li>Version 1 - january 2011 - Initial Release.</li>
</ul>